name: Testing

on:
  pull_request:
    branches: [ main ]

  push:
    branches: [ main ]

jobs:
  test_main:
    name: Test Main Branch
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.11.5'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run Pytest
        run: pytest
